apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: temporal-cloud
type: Opaque
stringData:
  POSTGRES_USER: temporal
  POSTGRES_PASSWORD: temporal_secret_change_me
  POSTGRES_DB: temporal
---
apiVersion: v1
kind: Secret
metadata:
  name: billing-secrets
  namespace: temporal-cloud
type: Opaque
stringData:
  STRIPE_SECRET_KEY: sk_test_your_stripe_key
  STRIPE_WEBHOOK_SECRET: whsec_your_webhook_secret
  DATABASE_URL: postgres://temporal:temporal_secret_change_me@postgres:5432/billing?sslmode=disable
---
apiVersion: v1
kind: Secret
metadata:
  name: temporal-secrets
  namespace: temporal-system
type: Opaque
stringData:
  POSTGRES_USER: temporal
  POSTGRES_PASSWORD: temporal_secret_change_me
