apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  namespace: temporal-cloud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
    spec:
      containers:
        - name: billing
          image: temporal-cloud/billing-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          envFrom:
            - secretRef:
                name: billing-secrets
          env:
            - name: PORT
              value: "8082"
            - name: TEMPORAL_ADDRESS
              value: temporal-server.temporal-system.svc.cluster.local:7233
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: billing-service
  namespace: temporal-cloud
spec:
  selector:
    app: billing-service
  ports:
    - port: 8082
      targetPort: 8082
