apiVersion: v1
kind: Namespace
metadata:
  name: temporal-cloud
---
apiVersion: v1
kind: Secret
metadata:
  name: billing-secrets
  namespace: temporal-cloud
type: Opaque
stringData:
  # Populate these with real Stripe values via kubectl create secret or your CI/CD system.
  STRIPE_SECRET_KEY: ""
  STRIPE_PRICE_ESSENTIAL: ""
  STRIPE_PRICE_BUSINESS: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  namespace: temporal-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
    spec:
      containers:
        - name: billing
          image: docker.io/library/billing-service:amd64
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: DATABASE_URL
              value: "postgres://temporal:temporal@postgresql.temporal.svc.cluster.local:5432/billing?sslmode=disable"
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: billing-secrets
                  key: STRIPE_SECRET_KEY
            - name: STRIPE_PRICE_ESSENTIAL
              valueFrom:
                secretKeyRef:
                  name: billing-secrets
                  key: STRIPE_PRICE_ESSENTIAL
            - name: STRIPE_PRICE_BUSINESS
              valueFrom:
                secretKeyRef:
                  name: billing-secrets
                  key: STRIPE_PRICE_BUSINESS
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: billing-service
  namespace: temporal-cloud
spec:
  type: NodePort
  selector:
    app: billing-service
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30082
