apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-server
  namespace: temporal-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-server
  template:
    metadata:
      labels:
        app: temporal-server
    spec:
      containers:
        - name: temporal
          image: temporalio/auto-setup:latest
          ports:
            - containerPort: 7233
            - containerPort: 7234
            - containerPort: 7235
            - containerPort: 7239
          env:
            - name: DB
              value: postgres12
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: temporal
            - name: POSTGRES_PWD
              value: temporal123
            - name: POSTGRES_SEEDS
              value: postgres.temporal-cloud.svc.cluster.local
            - name: DYNAMIC_CONFIG_FILE_PATH
              value: config/dynamicconfig/development-sql.yaml
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: temporal
  namespace: temporal-cloud
spec:
  type: NodePort
  selector:
    app: temporal-server
  ports:
    - name: grpc
      port: 7233
      targetPort: 7233
      nodePort: 30233
    - name: metrics
      port: 7239
      targetPort: 7239
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-ui
  namespace: temporal-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-ui
  template:
    metadata:
      labels:
        app: temporal-ui
    spec:
      containers:
        - name: temporal-ui
          image: temporalio/ui:latest
          ports:
            - containerPort: 8080
          env:
            - name: TEMPORAL_ADDRESS
              value: temporal.temporal-cloud.svc.cluster.local:7233
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-ui
  namespace: temporal-cloud
spec:
  type: NodePort
  selector:
    app: temporal-ui
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
