apiVersion: v1
kind: Namespace
metadata:
  name: temporal-system
  labels:
    app.kubernetes.io/name: temporal-system
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: temporal-cloud
  labels:
    app.kubernetes.io/name: temporal-cloud
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: temporal-cloud-quota
  namespace: temporal-cloud
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: temporal-cloud-limits
  namespace: temporal-cloud
spec:
  limits:
    - default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      type: Container
