apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: temporal-cloud
type: Opaque
stringData:
  POSTGRES_USER: temporal
  POSTGRES_PASSWORD: "temporal_prod_8f3a2b1c"
  POSTGRES_DB: temporal
---
apiVersion: v1
kind: Secret
metadata:
  name: billing-secrets
  namespace: temporal-cloud
type: Opaque
stringData:
  STRIPE_SECRET_KEY: "sk_test_placeholder_update_me"
  STRIPE_WEBHOOK_SECRET: "whsec_placeholder_update_me"
  DATABASE_URL: "postgres://temporal:temporal_prod_8f3a2b1c@postgres:5432/billing?sslmode=disable"
---
apiVersion: v1
kind: Secret
metadata:
  name: temporal-secrets
  namespace: temporal-system
type: Opaque
stringData:
  POSTGRES_USER: temporal
  POSTGRES_PASSWORD: "temporal_prod_8f3a2b1c"
