apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-dynamic-config
  namespace: temporal-system
data:
  dynamicconfig.yaml: |
    system.forceSearchAttributesCacheRefreshOnRead:
      - value: true
    frontend.enableClientVersionCheck:
      - value: false
    history.defaultActivityRetryPolicy:
      - value:
          InitialIntervalInSeconds: 1
          MaximumIntervalCoefficient: 100.0
          BackoffCoefficient: 2.0
          MaximumAttempts: 0
    limit.maxIDLength:
      - value: 1000
    frontend.keepAliveMaxConnectionAge:
      - value: 5m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-server
  namespace: temporal-system
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: temporal-server
  template:
    metadata:
      labels:
        app: temporal-server
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - temporal-server
                topologyKey: kubernetes.io/hostname
      containers:
        - name: temporal
          image: temporalio/auto-setup:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7233
              name: grpc
            - containerPort: 7234
              name: grpc-web
            - containerPort: 7235
              name: membership
            - containerPort: 9090
              name: metrics
          env:
            - name: DB
              value: postgresql
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_HOST
              value: postgres.temporal-cloud.svc.cluster.local
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: temporal-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PWD
              valueFrom:
                secretKeyRef:
                  name: temporal-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_SEEDS
              value: postgres.temporal-cloud.svc.cluster.local
            - name: DYNAMIC_CONFIG_FILE_PATH
              value: /etc/temporal/config/dynamicconfig.yaml
            - name: ENABLE_ES
              value: "false"
            - name: PROMETHEUS_ENDPOINT
              value: "0.0.0.0:9090"
            - name: NUM_HISTORY_SHARDS
              value: "512"
          volumeMounts:
            - name: dynamic-config
              mountPath: /etc/temporal/config
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          livenessProbe:
            tcpSocket:
              port: 7233
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: 7233
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: dynamic-config
          configMap:
            name: temporal-dynamic-config
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-server
  namespace: temporal-system
spec:
  selector:
    app: temporal-server
  ports:
    - name: grpc
      port: 7233
      targetPort: 7233
    - name: grpc-web
      port: 7234
      targetPort: 7234
    - name: metrics
      port: 9090
      targetPort: 9090
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: temporal-server-pdb
  namespace: temporal-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: temporal-server
