apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  namespace: temporal-cloud
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - billing-service
                topologyKey: kubernetes.io/hostname
      containers:
        - name: billing
          image: ghcr.io/temporal-cloud/billing-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: PORT
              value: "8082"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: billing-secrets
                  key: DATABASE_URL
            - name: TEMPORAL_ADDRESS
              value: temporal-server.temporal-system.svc.cluster.local:7233
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: billing-secrets
                  key: STRIPE_SECRET_KEY
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: billing-secrets
                  key: STRIPE_WEBHOOK_SECRET
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: billing-service
  namespace: temporal-cloud
spec:
  selector:
    app: billing-service
  ports:
    - port: 8082
      targetPort: 8082
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: billing-service-pdb
  namespace: temporal-cloud
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: billing-service
