# Marketing Site Deployment for Temporal Cloud
# Serves static SvelteKit build via nginx
# After login, users access the dashboard which proxies to Temporal UI
apiVersion: v1
kind: ConfigMap
metadata:
  name: marketing-nginx-config
  namespace: temporal-cloud
data:
  nginx.conf: |
    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;
        index index.html;

        # Gzip compression
        gzip on;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml;

        # Static assets with long cache
        location /_app/ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }

        # SPA fallback - serve index.html for all routes
        location / {
            try_files $uri $uri.html $uri/ /index.html;
        }

        # Proxy /temporal to Temporal UI (using resolver for dynamic DNS)
        resolver kube-dns.kube-system.svc.cluster.local valid=10s;
        
        location /temporal/ {
            set $temporal_ui temporal-ui.temporal-cloud.svc.cluster.local;
            proxy_pass http://$temporal_ui:8080/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketing-site
  namespace: temporal-cloud
  labels:
    app: marketing-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketing-site
  template:
    metadata:
      labels:
        app: marketing-site
    spec:
      initContainers:
        # Download and extract the marketing site build
        - name: fetch-site
          image: alpine:latest
          command:
            - sh
            - -c
            - |
              apk add --no-cache curl tar
              # For now, create a simple landing page
              # In production, fetch from a release URL or use a proper image
              mkdir -p /site/_app
              cat > /site/index.html << 'EOF'
              <!DOCTYPE html>
              <html lang="en">
              <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Temporal Cloud</title>
                <script src="https://cdn.tailwindcss.com"></script>
              </head>
              <body class="bg-[#0d1117] text-white min-h-screen">
                <nav class="border-b border-zinc-800 px-6 py-4">
                  <div class="max-w-7xl mx-auto flex justify-between items-center">
                    <span class="text-xl font-bold">Temporal Cloud</span>
                    <div class="flex gap-4">
                      <a href="/temporal/" class="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 rounded-lg">Open Console</a>
                    </div>
                  </div>
                </nav>
                <main class="max-w-7xl mx-auto px-6 py-24">
                  <div class="text-center">
                    <h1 class="text-5xl font-bold mb-6">What if your code never failed?</h1>
                    <p class="text-xl text-zinc-400 mb-10 max-w-2xl mx-auto">
                      Failures happen. Temporal makes them irrelevant. Build applications that never lose state.
                    </p>
                    <a href="/temporal/" class="inline-block px-8 py-4 bg-gradient-to-r from-emerald-400 to-cyan-400 text-black font-semibold rounded-lg text-lg">
                      Get Started
                    </a>
                  </div>
                </main>
              </body>
              </html>
              EOF
          volumeMounts:
            - name: site-content
              mountPath: /site
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
            - name: site-content
              mountPath: /usr/share/nginx/html
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 10
      volumes:
        - name: nginx-config
          configMap:
            name: marketing-nginx-config
        - name: site-content
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: marketing-site
  namespace: temporal-cloud
spec:
  selector:
    app: marketing-site
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
