# Temporal Server for OKE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal
  namespace: temporal-cloud
  labels:
    app: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal
  template:
    metadata:
      labels:
        app: temporal
    spec:
      containers:
        - name: temporal
          image: temporalio/auto-setup:latest
          ports:
            - containerPort: 7233
              name: grpc
            - containerPort: 7234
              name: grpc-frontend
            - containerPort: 7235
              name: grpc-matching
            - containerPort: 7239
              name: metrics
          env:
            - name: DB
              value: postgresql
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: temporal
            - name: POSTGRES_PWD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POSTGRES_SEEDS
              value: postgresql.temporal-cloud.svc.cluster.local
            - name: DYNAMIC_CONFIG_FILE_PATH
              value: /etc/temporal/config/dynamicconfig/development-sql.yaml
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          livenessProbe:
            tcpSocket:
              port: 7233
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 7233
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: temporal
  namespace: temporal-cloud
spec:
  selector:
    app: temporal
  ports:
    - name: grpc
      port: 7233
      targetPort: 7233
    - name: metrics
      port: 7239
      targetPort: 7239
---
# Temporal UI
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-ui
  namespace: temporal-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-ui
  template:
    metadata:
      labels:
        app: temporal-ui
    spec:
      containers:
        - name: temporal-ui
          image: temporalio/ui:latest
          ports:
            - containerPort: 8080
          env:
            - name: TEMPORAL_ADDRESS
              value: temporal.temporal-cloud.svc.cluster.local:7233
            - name: TEMPORAL_CORS_ORIGINS
              value: "*"
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-ui
  namespace: temporal-cloud
spec:
  selector:
    app: temporal-ui
  ports:
    - port: 8080
      targetPort: 8080
